from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
COMMANDS_FILE = PROJECT_ROOT / "commands.json"
STATE_FILE = PROJECT_ROOT / "state.json"
APP_VERSION = "2.0.0"

BREAKPOINT_WIDTH = 410

APP_WIDTH = 420
APP_HEIGHT = 220
APP_MIN_WIDTH = 220
APP_MIN_HEIGHT = 165

STATUS_UPDATE_MS = 10_000
WEATHER_UPDATE_MS = 30 * 60_000

APP_TITLE = "M87 Terminal"
FONT_FAMILY = "JetBrains Mono"
